CREATE USER usuario IDENTIFIED BY pass
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO usuario;
GRANT CREATE TABLE TO usuario;
GRANT CREATE VIEW TO usuario;
GRANT CREATE ANY TRIGGER TO usuario;
GRANT CREATE ANY PROCEDURE TO usuario;
GRANT UNLIMITED TABLESPACE TO usuario;


SELECT username
FROM dba_users
WHERE username = 'USUARIO';

